# Introduction

**Learning objectives:**

- Describe what this book is about! 

- Run R in **interactive mode**, **batch mode** and **semi-interactive mode**

- Create, import and work with one of the basic data types: **numeric vector**

## Preface 1 {-}

- R is a language and an environment

  * Graphics capabilities. 
  * Help system. 
  * Interface to compiled code. 
  * A package systenm + package repositories (CRAN) 
  * A 👌 lively community!
  
## Preface 2 {-}

The author does not like: 

- the way R is taught in a stats course 

- the tidyverse

He advocates for an approach that could help us solve every data intense problem and acquire skills relevant to other languages. 

## Preface 3 {-}

The book follow more more data types approach than a workflow approach. 

1. Basic types: 
    * Atomic: logical (TRUE/FALSE), numeric, character. 
    * Function. 
    * List. 

2. Compound types: 
    * Factor. 
    * Matrix. 
    * data.frame.  
    * formula. 
    
3. Advanced material: 
  * Symbol, call, expressions: metaprograming. 
  * Environment: scoping / store/access objects   
  * Interface compiled code

## Introduction 1. {-}

### Interactive mode

Go into R and use `cat()` ! 

`>` see the prompt 

`+` is for more

and we can use `ESC` or `CTRL+C` to abord input! 

### Batch mode

```{bash, eval=FALSE}
Rscript file.R
```

should we do a demo?

### Semi interactive: 

- JupyterLab

- Rmarkdown 

- org-mode 
